import React from 'react';
import { useNavigate } from 'react-router-dom';
import './AuthPages.css'; // Reusing auth page styles for consistency
import './RefundPolicy.css'; // Specific overrides

const RefundPolicy = () => {
    const navigate = useNavigate();

    return (
        <div className="auth-container policy-page">
            <div className="auth-box policy-box">
                <button className="back-btn" onClick={() => navigate('/')}>← Back to Home</button>

                <h1>Refund Policy & Terms</h1>
                <p className="last-updated">Last Updated: January 16, 2026</p>

                <div className="policy-content">
                    <section>
                        <h2>1. Legal Disclaimer (Important)</h2>
                        <p><strong>CONTRACT READER IS AN AI-POWERED TOOL, NOT A LAW FIRM.</strong></p>
                        <p>
                            The information, analysis, summaries, and letters generated by this application are for <strong>informational purposes only</strong> and do NOT constitute legal advice.
                            We are not attorneys, and no attorney-client relationship is formed by your use of this service.
                        </p>
                        <p>
                            You are solely responsible for reviewing all generated content for accuracy and legality before using it.
                            You should consult with a qualified attorney for advice on your specific legal situation.
                        </p>
                    </section>

                    <section>
                        <h2>2. No Warranty</h2>
                        <p>
                            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE," WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND.
                        </p>
                        <p>
                            WE EXPRESSLY DISCLAIM ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, OR STATUTORY, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
                            WE DO NOT WARRANT THAT THE AI ANALYSIS WILL BE ERROR-FREE, ACCURATE, OR COMPLETE.
                        </p>
                    </section>

                    <section>
                        <h2>3. Limitation of Liability</h2>
                        <p>
                            TO THE EXTENT PERMITTED BY LAW, CONTRACT READER AND ITS OWNERS SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES, INCLUDING BUT NOT LIMITED TO DAMAGES FOR LOSS OF PROFITS, GOODWILL, USE, DATA, OR OTHER INTANGIBLE LOSSES, RESULTING FROM YOUR USE OF THE SERVICE.
                        </p>
                        <p>
                            OUR TOTAL LIABILITY FOR ANY CLAIM ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICE SHALL NOT EXCEED THE AMOUNT YOU PAID TO US FOR THE SERVICE IN THE SIX (6) MONTHS PRECEDING THE CLAIM.
                        </p>
                    </section>

                    <section>
                        <h2>4. Consumer Protection Act (CPA) Compliance</h2>
                        <p>
                            If you are a consumer in South Africa, you have certain rights under the Consumer Protection Act 68 of 2008 (CPA).
                            Nothing in these terms is intended to unlawfully restrict, limit, or avoid any rights or obligations created for either you or us in terms of the CPA.
                        </p>
                        <p>
                            <strong>Cooling-off Period:</strong> In terms of Section 16 of the CPA, if this transaction resulted from direct marketing, you may rescind the transaction without reason or penalty within 5 business days.
                        </p>
                    </section>

                    <section>
                        <h2>5. Refund Policy</h2>
                        <p>
                            We offer refunds under the following conditions, subject to our discretion and applicable laws:
                        </p>
                        <ul>
                            <li><strong>Technical Failure:</strong> If the service failed to process your document due to a verified technical error on our end.</li>
                            <li><strong>Double Billing:</strong> If you were accidentally charged twice for the same transaction.</li>
                        </ul>
                        <p>
                            <strong>Non-Refundable Circumstances:</strong>
                        </p>
                        <ul>
                            <li>Dissatisfaction with the AI's legal interpretation (as this is subjective and informational).</li>
                            <li>Failure to cancel a subscription before the renewal date.</li>
                            <li>Change of mind after the service has been delivered.</li>
                        </ul>
                    </section>

                    <section>
                        <h2>6. Subscription Cancellation</h2>
                        <p>
                            You may cancel your Premium subscription at any time via your account settings.
                            Cancellation takes effect at the end of the current billing period. You will not be charged again, but no prorated refunds are issued for the remainder of the current period.
                        </p>
                    </section>

                    <section>
                        <h2>7. Contact Us</h2>
                        <p>
                            For refund requests or legal inquiries, please contact: <strong>evolutionmediasa@gmail.com</strong>
                        </p>
                    </section>
                </div>
            </div>
        </div>
    );
};

export default RefundPolicy;
